

server:
  port: 2020

spring:
  application:
    name: mysql_learn_demo

  # 数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/banyechan?characterEncoding=utf8&useSSL=false



# mybaits 模块配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.banyechen.mysql_learn_demo.entity


#sql语句打印
logging:
  level:
    com:
      banyechen:
        mysql_learn_demo:
          mapper: debug

